name: "Test Assistant"

runs:
  using: "composite"
  steps:
    - name: Run Tests
      shell: bash -l {0}
      env:
        PYTHONUNBUFFERED: "1"
        FORCE_COLOR: "1"
      run: |
        chmod +x ./.github/workflow_scripts/test_assistant.sh && ./.github/workflow_scripts/test_assistant.sh
