name: Continuous Integration
on:
  push:
  pull_request_target:
    types: [labeled, synchronize, opened]

permissions:
  id-token: write
  contents: read
  pull-requests: write # for removing tags

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.event.pull_request.head.sha }}
  cancel-in-progress: true

jobs:
  permission_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Actor Permission
        id: check
        continue-on-error: true
        uses: prince-chrismc/check-actor-permissions-action@v3
        with:
          github_token: ${{ github.token }}
          permission: write
      - name: Debug Information
        if: ${{ github.event_name == 'pull_request_target' }}
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Labels: ${{ toJson(github.event.pull_request.labels) }}"
          echo "Permitted: ${{ steps.check.outputs.permitted }}"
          echo "Safe to Test Label Present: ${{ contains(github.event.pull_request.labels.*.name, 'safe to test') }}"
      - name: Check PR Safe to Run
        if: ${{ github.event_name == 'pull_request_target' && !contains(github.event.pull_request.labels.*.name, 'safe to test') && steps.check.outputs.permitted == 'false' }}
        run: exit 1
  integration_test:
    needs: permission_check
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: ["3.10"]

    steps:
      - name: Checkout repository
        if: ${{ github.event_name != 'pull_request_target' }}
        uses: actions/checkout@v4

      - name: Checkout repository(Pull Request Target)
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: actions/checkout@v4

      - name: Integration Test
        uses: ./.github/actions/test-assistant
        
